GenerateFundModel/Models/Borrower.cs
namespace FundClear.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Borrower")]
    public partial class Borrower
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Borrower()
        {
            Fix_Product = new HashSet<Fix_Product>();
        }

        [Key]
        public int Borrower_id { get; set; }

        [StringLength(200)]
        public string 融资方名字 { get; set; }

        [StringLength(200)]
        public string 融资方开户银行 { get; set; }

        [StringLength(200)]
        public string 融资方账户名 { get; set; }

        [StringLength(200)]
        public string 融资方银行账号 { get; set; }

        [StringLength(200)]
        public string 融资方电话 { get; set; }

        [StringLength(200)]
        public string 融资方电邮 { get; set; }

        [StringLength(500)]
        public string 融资方地址 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fix_Product> Fix_Product { get; set; }
    }
}

GenerateFundModel/Controllers/BorrowersController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FundClear.Models;
using PagedList;

namespace FundClear.Controllers
{
    public class BorrowersController : Controller
    {
        private Fund db = new Fund();
        [Authorize]
        // GET: Student
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
          
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var borrowers = from s in db.Borrower select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                borrowers = borrowers.Where(s => s.融资方名字.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    borrowers = borrowers.OrderByDescending(s => s.融资方名字);
                    break;                
                default:  // Name ascending 
                    borrowers = borrowers.OrderBy(s => s.融资方名字);
                    break;
            }

            int pageSize = Config.pageSize;
            int pageNumber = (page ?? 1);
            return View(borrowers.ToPagedList(pageNumber, pageSize));
        }
        [Authorize]
        // GET: Borrowers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Borrower borrower = db.Borrower.Find(id);
            if (borrower == null)
            {
                return HttpNotFound();
            }
            return View(borrower);
        }

        // GET: Borrowers/Create
        public ActionResult Create()
        {
            return View();
        }
        [Authorize]
        // POST: Borrowers/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Borrower_id,融资方名字,融资方开户银行,融资方账户名,融资方银行账号,融资方电话,融资方电邮,融资方地址")] Borrower borrower)
        {
            if (ModelState.IsValid)
            {
                db.Borrower.Add(borrower);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(borrower);
        }
        [Authorize]
        // GET: Borrowers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Borrower borrower = db.Borrower.Find(id);
            if (borrower == null)
            {
                return HttpNotFound();
            }
            return View(borrower);
        }
        [Authorize]
        // POST: Borrowers/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Borrower_id,融资方名字,融资方开户银行,融资方账户名,融资方银行账号,融资方电话,融资方电邮,融资方地址")] Borrower borrower)
        {
            if (ModelState.IsValid)
            {
                db.Entry(borrower).State = EntityState.Modified;
                db.SaveChanges();
                string url = Request.QueryString["returnurl"] != null ? Request.QueryString["returnurl"].ToString() : "";
                if (url != "")
                    Response.Redirect(url);
                else
                    return RedirectToAction("Index"); 
            }
            return View(borrower);
        }
        [Authorize]
        // GET: Borrowers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Borrower borrower = db.Borrower.Find(id);
            if (borrower == null)
            {
                return HttpNotFound();
            }
            return View(borrower);
        }
        [Authorize]
        // POST: Borrowers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Borrower borrower = db.Borrower.Find(id);
            db.Borrower.Remove(borrower);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GenerateFundModel/Views/Borrowers/Create.cshtml
@model FundClear.Models.Borrower

@{
    ViewBag.Title = "新建";
}

<h2>新建</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>融资方</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.融资方名字, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方名字, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方名字, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方开户银行, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方开户银行, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方开户银行, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方账户名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方账户名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方账户名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方银行账号, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方银行账号, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方银行账号, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方电话, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方电话, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方电话, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方电邮, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方电邮, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方电邮, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GenerateFundModel/Views/Borrowers/Delete.cshtml
@model FundClear.Models.Borrower

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Borrower</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.融资方名字)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方名字)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方开户银行)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方开户银行)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方账户名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方账户名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方银行账号)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方银行账号)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方电话)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方电话)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方电邮)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方电邮)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GenerateFundModel/Views/Borrowers/Details.cshtml
@model FundClear.Models.Borrower

@{
    ViewBag.Title = "融资方详情";
}

<h2>详情</h2>

<div>
    <h4>融资方</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.融资方名字)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方名字)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方开户银行)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方开户银行)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方账户名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方账户名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方银行账号)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方银行账号)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方电话)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方电话)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方电邮)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方电邮)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.融资方地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.融资方地址)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("编辑", "Edit", new { id = Model.Borrower_id }) |
    @Html.ActionLink("返回列表", "Index")
</p>

GenerateFundModel/Views/Borrowers/Edit.cshtml
@model FundClear.Models.Borrower

@{
    ViewBag.Title = "融资方编辑";
}

<h2>编辑</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>融资方</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Borrower_id)

        <div class="form-group">
            @Html.LabelFor(model => model.融资方名字, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方名字, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方名字, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方开户银行, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方开户银行, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方开户银行, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方账户名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方账户名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方账户名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方银行账号, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方银行账号, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方银行账号, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方电话, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方电话, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方电话, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方电邮, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方电邮, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方电邮, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.融资方地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.融资方地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.融资方地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="保存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GenerateFundModel/Views/Borrowers/Index.cshtml
@model PagedList.IPagedList<FundClear.Models.Borrower>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script>
    $(document).ready(function(){
    $("#btnSubmit").click(function () {
        var strFilter = "";
        if ($("#SearchString").val().trim() != "")
            strFilter += "&searchString=" + escape($("#SearchString").val());
        location.href = "/Borrowers?page=1" + strFilter;
    });
    })
</script>
@{
    ViewBag.Title = "融资方列表";
}

<h2>融资方列表</h2>

<p>
    @Html.ActionLink("新建", "Create")
</p>
@using (Html.BeginForm("Index", "Borrowers", FormMethod.Post))
{
    <p>
        按名称查找: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string) 
        <input type="button" id="btnSubmit" value="查找" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("融资方名称", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            电话
        </th>
        <th>
            电邮
        </th>
        <th>
            地址
        </th>
       
        <th></th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.融资方名字)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.融资方电话)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.融资方电邮)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.融资方地址)
            </td>
           
            <td>
                @Html.ActionLink("编辑", "Edit", new { id = item.Borrower_id, returnurl = @Request.Url }) |
                @Html.ActionLink("详情", "Details", new { id = item.Borrower_id }) |
                @Html.ActionLink("删除", "Delete", new { id = item.Borrower_id })
            </td>
        </tr>
    }

</table>
<br />
页面 @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))